### ISSUE TITLE
Can't install canvas-sketch-cli on linux

### ISSUE THREAD

**Issue by shardulpathak7** [mattdesl/workshop-generative-art#10]
OS ubuntu 18.04
Have no problem install other npm packages
This is the error:
``
sudo npm install canvas-sketch-cli --global
[sudo] password for shardul: 
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/bin/canvas-sketch -> /usr/lib/node_modules/canvas-sketch-cli/src/index.js
/usr/bin/canvas-sketch-cli -> /usr/lib/node_modules/canvas-sketch-cli/src/index.js
/usr/bin/canvas-sketch-gif -> /usr/lib/node_modules/canvas-sketch-cli/src/ffmpeg-gif.js
/usr/bin/canvas-sketch-mp4 -> /usr/lib/node_modules/canvas-sketch-cli/src/ffmpeg-mp4.js

> registry-js@1.9.0 install /usr/lib/node_modules/canvas-sketch-cli/node_modules/registry-js
> prebuild-install || node-gyp rebuild

prebuild-install WARN install No prebuilt binaries found (target=12.16.1 runtime=node arch=x64 libc= platform=linux)
gyp ERR! clean error 
gyp ERR! stack Error: EACCES: permission denied, rmdir 'build'
gyp ERR! System Linux 5.3.0-40-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /usr/lib/node_modules/canvas-sketch-cli/node_modules/registry-js
gyp ERR! node -v v12.16.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok 
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/canvas-sketch-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! registry-js@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the registry-js@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/shardul/.npm/_logs/2020-05-15T18_00_39_802Z-debug.log
``

**Comment by MGarrod1** [comment]
I'm also on Ubuntu 18.04 and am getting a similar error. I've tried this both with node V8.1.0 & 12.18.2 and a similar issue seems to occur.

"""
sudo npm install canvas-sketch-cli --global
[sudo] password for matt: 
npm WARN deprecated chokidar@2.1.8: Chokidar 2 will break on node v14+. Upgrade to chokidar 3 with 15x less dependencies.
npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
npm WARN deprecated resolve-url@0.2.1: https://github.com/lydell/resolve-url#deprecated
npm WARN deprecated urix@0.1.0: Please see https://github.com/lydell/urix#deprecated
npm WARN deprecated core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
/usr/local/bin/canvas-sketch -> /usr/local/lib/node_modules/canvas-sketch-cli/src/index.js
/usr/local/bin/canvas-sketch-cli -> /usr/local/lib/node_modules/canvas-sketch-cli/src/index.js
/usr/local/bin/canvas-sketch-gif -> /usr/local/lib/node_modules/canvas-sketch-cli/src/ffmpeg-gif.js
/usr/local/bin/canvas-sketch-mp4 -> /usr/local/lib/node_modules/canvas-sketch-cli/src/ffmpeg-mp4.js
npm WARN lifecycle The node binary used for scripts is /snap/bin/node but npm is using /snap/node/2799/bin/node itself. Use the `--scripts-prepend-node-path` option to include the path for the node binary npm was executed with.

> registry-js@1.9.0 install /usr/local/lib/node_modules/canvas-sketch-cli/node_modules/registry-js
> prebuild-install || node-gyp rebuild

2020/07/14 07:53:52.946041 cmd_run.go:918: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/2799": mkdir /nonexistent: permission denied
cannot create user data directory: /nonexistent/snap/node/2799: Permission denied
2020/07/14 07:53:52.975562 cmd_run.go:918: WARNING: cannot create user data directory: cannot create "/nonexistent/snap/node/2799": mkdir /nonexistent: permission denied
cannot create user data directory: /nonexistent/snap/node/2799: Permission denied
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/canvas-sketch-cli/node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! registry-js@1.9.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the registry-js@1.9.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/matt/.npm/_logs/2020-07-14T06_53_53_780Z-debug.log
"""

**Comment by MGarrod1** [comment]
I've also just tried the local install suggested at: [https://github.com/mattdesl/workshop-generative-art/issues/11](https://github.com/mattdesl/workshop-generative-art/issues/11) 

I ran: 
_cd project_for_local
npm init -y
npm install canvas-sketch-cli --save-dev_

And end up with a similar error again:

> sudo npm install canvas-sketch-cli --save-dev
> npm WARN deprecated fsevents@1.2.13: fsevents 1 will break on node v14+ and could be using insecure binaries. Upgrade to fsevents 2.
> 
> > registry-js@1.9.0 install /home/matt/Dropbox/FrontEndMastersCourses/Creative_Coding/project_for_local/node_modules/registry-js
> > prebuild-install || node-gyp rebuild
> 
> prebuild-install WARN install No prebuilt binaries found (target=12.18.2 runtime=node arch=x64 libc= platform=linux)
> gyp ERR! build error 
> gyp ERR! stack Error: not found: make
> gyp ERR! stack     at getNotFoundError (/usr/lib/node_modules/npm/node_modules/which/which.js:13:12)
> gyp ERR! stack     at F (/usr/lib/node_modules/npm/node_modules/which/which.js:68:19)
> gyp ERR! stack     at E (/usr/lib/node_modules/npm/node_modules/which/which.js:80:29)
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/which/which.js:89:16
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/index.js:42:5
> gyp ERR! stack     at /usr/lib/node_modules/npm/node_modules/isexe/mode.js:8:5
> gyp ERR! stack     at FSReqCallback.oncomplete (fs.js:167:21)
> gyp ERR! System Linux 5.3.0-59-generic
> gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
> gyp ERR! cwd /home/matt/Dropbox/FrontEndMastersCourses/Creative_Coding/project_for_local/node_modules/registry-js
> gyp ERR! node -v v12.18.2
> gyp ERR! node-gyp -v v5.1.0
> gyp ERR! not ok 
> npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.2.7 (node_modules/chokidar/node_modules/fsevents):
> npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.13: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
> npm WARN project_for_local@1.0.0 No description
> npm WARN project_for_local@1.0.0 No repository field.
> 
> npm ERR! code ELIFECYCLE
> npm ERR! errno 1
> npm ERR! registry-js@1.9.0 install: `prebuild-install || node-gyp rebuild`
> npm ERR! Exit status 1
> npm ERR! 
> npm ERR! Failed at the registry-js@1.9.0 install script.
> npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /home/matt/.npm/_logs/2020-07-14T07_20_15_115Z-debug.log
>

**Comment by mattdesl** [comment]
Ok, I've finally pinpointed the issue—it has to do with the [downloads-folder](https://www.npmjs.com/package/downloads-folder) module which fails to install on some systems. Will see about switching that out with another module that has the same functionality, if possible.

**Comment by mattdesl** [comment]
Should be sorted in v1.11.9, if you could try to reinstall it globally (or locally if you're using it that way) like so:

```sh
npm install canvas-sketch-cli@1.11.9 --global
```

If any users are running into problems with the automatic Downloads folder resolution, you may want to set an environment variable, see [here](https://github.com/mattdesl/canvas-sketch/blob/master/docs/exporting-artwork.md#changing-the-output-folder).

Please let me know if that fixes it for you.

**Comment by MGarrod1** [comment]
That seems to have worked for me. 

Thanks!

**Comment by shardulpathak7** [comment]
It has worked for me.
Thanks!
